<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lab05">


    <xacro:property name="camera_size" value="0.05" />


    <link name="camera">

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${camera_size} ${camera_size} ${camera_size}" />
            </geometry>
        </collision>


        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${camera_size} ${camera_size} ${camera_size}" />
            </geometry>
            <material name="black" />
        </visual>


        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>

    </link>


    <joint name="camera_joint" type="fixed">
        <!-- <axis xyz="0 1 0" /> -->
        <origin xyz="0 0 ${camera_size/2 + chassis_height/2}" rpy="0 0 0" />
        <parent link="robot_chassis" />
        <child link="camera" />
    </joint>


</robot>
