<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lab05">


    <gazebo reference="robot_chassis">
        <material>Gazebo/DarkGray</material>
    </gazebo>

    <gazebo reference="left_wheel">
        <material>Gazebo/White</material>
    </gazebo>

    <gazebo reference="right_wheel">
        <material>Gazebo/White</material>
    </gazebo>

    <gazebo reference="front_glide">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="rear_glide">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="camera">
        <material>Gazebo/Red</material>
    </gazebo>



    <!-- Camera Plugin -->

    <xacro:property name="camera_update_hz" value="10" />

    <gazebo reference="camera">
        <sensor type="camera" name="camera1">
            <update_rate>${camera_update_hz}</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>lab05/camera1</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>



    <!-- Differential Drive Plugin -->
    <xacro:property name="diffdrive_update_hz" value="10" />
    <!-- TODO:
            parameterize elements below
     -->

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>${diffdrive_update_hz}</updateRate>
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${(chassis_radius - wheel_radius) * 2}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <torque>20</torque>
            <commandTopic>/lab05/cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>robot_chassis</robotBaseFrame>

            <legacyMode>false</legacyMode>
        </plugin>
    </gazebo>

</robot>
